sudo: false
cache:
  directories:
    - $HOME/download
    - $HOME/.cache/pip

language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"

before_install:
    - mkdir -p download
    - cd download
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - cd ..
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda config --set always_yes yes --set changeps1 no
    - conda update --q conda
    - conda install --yes pip
    - conda install --yes -c soft-matter ffmpeg=2.2.4
    - conda install --yes -c soft-matter pyav=v0.2.3.post0
    - conda install --yes -c menpo opencv=2.4.11
    - conda install --yes pyqtgraph
    - conda install --yes nose

install:
    - pip install -r requirements.txt

script:
    - python --version
    - nosetests

branches:
  only:
    - master

notifications:
  email: false
